version: '3.8'

services:
  # DEV
  pacmusic-dev:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: pacmusic-dev
    environment:
      MINIO_ENDPOINT: ${MINIO_DEV_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_DEV_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_DEV_SECRET_KEY}
    ports:
      - 5000:5000
    networks:
      - pacmusic-network

  # STG
  pacmusic-stg-1:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: pacmusic-stg-1
    environment:
      MINIO_ENDPOINT: ${MINIO_STG_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_STG_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_STG_SECRET_KEY}
    ports:
      - ${APP_STG_PORT_1}:5000
    networks:
      - pacmusic-network

  pacmusic-stg-2:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: pacmusic-stg-2
    environment:
      MINIO_ENDPOINT: ${MINIO_STG_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_STG_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_STG_SECRET_KEY}
    ports:
      - ${APP_STG_PORT_2}:5000
    networks:
      - pacmusic-network

  # PROD
  pacmusic-prod-1:
    image: "${APP_IMAGE}:${APP_TAG}"
    container_name: pacmusic-prod-1
    environment:
      MINIO_ENDPOINT: ${MINIO_PROD_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_PROD_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_PROD_SECRET_KEY}
    ports:
      - 5001:5000
    networks:
      - pacmusic-network

  pacmusic-prod-2:
    image: "${APP_IMAGE}:${APP_TAG}"
    container_name: pacmusic-prod-2
    environment:
      MINIO_ENDPOINT: ${MINIO_PROD_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_PROD_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_PROD_SECRET_KEY}
    ports:
      - 5004:5000
    networks:
      - pacmusic-network

  # NGINX Load Balancer
  nginx:
    image: nginx:latest
    container_name: nginx-loadbalancer
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - pacmusic-stg-1
      - pacmusic-stg-2
      - pacmusic-prod-1
      - pacmusic-prod-2
    networks:
      - pacmusic-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email didit@dwidi.dev --agree-tos --no-eff-email --force-renewal -d stg.dwidi.xyz -d dwidi.xyz
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    networks:
      - pacmusic-network

networks:
  pacmusic-network:
    driver: bridge

volumes:
  certs:
    driver: local
