name: Deploy Staging

on:
  push:
    branches:
      - main

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Add SSH key to the agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY_STAGING }}

      - name: Ensure SSH key is set up correctly
        run: |
          ssh -o StrictHostKeyChecking=no -T git@github.com || exit 1

      - name: Run deployment script on staging server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USER_NAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          script: |
            if [ ! -d "$APP_STG_PATH" ]; then
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              git clone git@github.com:dwididit/music-streaming.git $APP_STG_PATH
              cd $APP_STG_PATH
            else
              cd $APP_STG_PATH
              sudo docker-compose down --remove-orphans --timeout 60 pacmusic-stg || true
              git pull origin main
            fi

            # Ensure a .gitconfig exists
            touch ~/.gitconfig
            echo "[user]" >> ~/.gitconfig
            echo "    email = didit@dwidi.com" >> ~/.gitconfig
            echo "    name = Dwi Didit Prasetiyo" >> ~/.gitconfig

            # Set environment variables in .env file
            echo "APP_STG_PORT=${{ secrets.APP_STG_PORT }}" >> .env
            echo "MINIO_STG_ENDPOINT=${{ secrets.MINIO_STG_ENDPOINT }}" >> .env
            echo "MINIO_STG_ACCESS_KEY=${{ secrets.MINIO_STG_ACCESS_KEY }}" >> .env
            echo "MINIO_STG_SECRET_KEY=${{ secrets.MINIO_STG_SECRET_KEY }}" >> .env

            # Build and start Docker containers
            sudo docker-compose up --build -d pacmusic-stg

      - name: Wait for the application to start
        run: sleep 10

      - name: Test Hit Endpoint
        run: |
          curl -f ${{ secrets.STG_URL }}
