name: Deploy Production 🚀

on:
  release:
    types: [published, edited]

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}

      - name: Ensure correct file structure for Docker build
        run: |
          # Create the app directory
          mkdir -p app
          # Copy app.py and requirements.txt to the app directory if they exist
          if [ -f "app.py" ]; then
            cp app.py app/
          else
            echo "app.py not found!"
            exit 1
          fi
          if [ -f "requirements.txt" ]; then
            cp requirements.txt app/
          else
            echo "requirements.txt not found!"
            exit 1
          fi

      - name: Build Docker image
        run: docker build -t pacmusic-prod:latest -f app/Dockerfile app

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag pacmusic-prod:latest ${{ secrets.DOCKERHUB_USERNAME }}/pacmusic:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pacmusic:latest

      - name: Run deployment script on production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USER_NAME_PRODUCTION }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
          script: |
            APP_PROD_PATH="/home/ubuntu/production"
            if [ -d "$APP_PROD_PATH" ]; then
              cd $APP_PROD_PATH
              sudo docker-compose down --remove-orphans --timeout 60 pacmusic-prod || true
              git pull origin main
            else
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              git clone ${{ secrets.GIT_URL }} $APP_PROD_PATH
              cd $APP_PROD_PATH
            fi
            touch .env
            echo "APP_PROD_PORT=${{ secrets.APP_PROD_PORT }}" >> .env
            echo "MINIO_PROD_ENDPOINT=${{ secrets.MINIO_PROD_ENDPOINT }}" >> .env
            echo "MINIO_PROD_ACCESS_KEY=${{ secrets.MINIO_PROD_ACCESS_KEY }}" >> .env
            echo "MINIO_PROD_SECRET_KEY=${{ secrets.MINIO_PROD_SECRET_KEY }}" >> .env
            echo "APP_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/pacmusic" >> .env
            echo "APP_TAG=latest" >> .env
            sudo docker-compose --env-file .env up --detach pacmusic-prod

      - name: Wait for the application to start
        run: sleep 30

      - name: Get Docker logs
        run: |
          sudo docker ps -a
          sudo docker logs pacmusic-prod

      - name: Test Hit Endpoint
        run: curl -f ${{ secrets.PROD_URL }}
