name: Dev Testing 🔎

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: dev-testing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          cat <<EOT > .env
          MINIO_DEV_ENDPOINT=api-dev.minio-devops-class.pacmann.ai
          MINIO_DEV_ACCESS_KEY=pgxr3lnKHj4mxI7f69y9
          MINIO_DEV_SECRET_KEY=KBy9zfXscFDsbI5FWKJEWUPz6VpefDXagioj6rtF
          MINIO_STG_ENDPOINT=api-stg.minio-devops-class.pacmann.ai
          MINIO_STG_ACCESS_KEY=L8TO4LudnGJyMCWQ4F6Y
          MINIO_STG_SECRET_KEY=qGcII3Qb2cAUJTYhsoKztY4NE2wNV0GTdkn3zKLJ
          APP_STG_PORT=5001
          MINIO_PROD_ENDPOINT=api-prod.minio-devops-class.pacmann.ai
          MINIO_PROD_ACCESS_KEY=1EApWjUnu7YPW8XGU9K8
          MINIO_PROD_SECRET_KEY=yS9awRgYZ0zJAq69fwlYhZSYj5ypzoCB3Z2oLlOF
          APP_PROD_PORT=5000
          EOT

      - name: Build and Run application
        run: sudo docker-compose up --build --detach pacmusic-dev

      - name: Test Hit Endpoint
        run: |
          sleep 10
          curl http://localhost:5000

      - name: Install testing requirements
        run: pip install -r test/requirements.txt

      - name: Run tests
        run: python3 test/test.py
