name: Dev Testing 🔎

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: dev-testing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file for dev
        run: |
          echo "MINIO_DEV_ENDPOINT=api-dev.minio-devops-class.pacmann.ai" > .env
          echo "MINIO_DEV_ACCESS_KEY=pgxr3lnKHj4mxI7f69y9" >> .env
          echo "MINIO_DEV_SECRET_KEY=KBy9zfXscFDsbI5FWKJEWUPz6VpefDXagioj6rtF" >> .env

      - name: Build and Run application
        run: sudo docker-compose up --build --detach pacmusic-dev

      - name: Test Hit Endpoint
        run: |
          sleep 10
          curl http://localhost:5000

      - name: Install testing requirements
        run: pip install -r test/requirements.txt

      - name: Run tests
        run: python3 test/test.py
