name: Push to Container Registry 🛒

on:
  push:
    tags:
      - '*'

jobs:
  push-to-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Move requirements.txt if necessary
        run: |
          if [ -f "app/requirements.txt" ]; then
            mv app/requirements.txt requirements.txt
          fi

      - name: Build and Push Docker Image
        run: |
          TAG=${GITHUB_REF##*/}
          docker buildx build --push --file ./app/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/pacmusic:${TAG} --tag ${{ secrets.DOCKERHUB_USERNAME }}/pacmusic:latest .
