name: Push to Container Registry 🛒

on:
  push:
    tags:
      - '*'

jobs:
  push-to-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Images
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/pacmusic
          TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          docker buildx build --platform linux/amd64,linux/arm64 --push -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .
